name: Training pipeline
on:
  workflow_dispatch:
    inputs:
      update_best_model:
        type: choice
        description: update best model?
        options: 
        - True
        - False


jobs:
  get_and_clean_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - uses: actions/setup-python@v4 # THIS IS IMPORTANT
      with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
    - name: get and clean habr data
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        pip install -r requirements.txt
        python3 get_data.py

  vectorize_text:
    needs: get_and_clean_data
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - name: vectorize_text
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        sudo apt update
        sudo apt install python3.9
        pip install -r requirements_runner.txt
        python3 vectorize_text.py

  train_models:
    if: github.event.inputs.update_best_model == 'False'
    needs: vectorize_text
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - name: train_models
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        sudo apt update
        sudo apt install python3.9
        pip install -r requirements_runner.txt
        python3 train.py

  update_models:
    if: github.event.inputs.update_best_model == 'True'
    needs: vectorize_text
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - name: train_models
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        sudo apt update
        sudo apt install python3.9
        pip install -r requirements_runner.txt
        python3 update_best_model.py
        
  optimize_model:
    if: ${{ always() }}
    needs: [train_models, update_models]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - name: optimize_model
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        sudo apt update
        sudo apt install python3.9
        pip install -r requirements_runner.txt
        python3 optimize_best_model.py  
        
  deploy:
    needs: [optimize_model]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - name: deploy
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        sudo apt update
        sudo apt install python3.9
        pip install -r requirements_runner.txt
        kill -9 $(sudo lsof -t -i:32846) || true
        RUNNER_TRACKING_ID="" && nohup uvicorn web_inference:app --host 0.0.0.0 --port 32846 &
