name: Training pipeline
on:
  workflow_dispatch:


jobs:
  get_and_clean_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - uses: actions/setup-python@v4 # THIS IS IMPORTANT
      with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
    - name: get and clean habr data
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        pip install -r requirements.txt
        python3 get_data.py

  vectorize_text:
    needs: get_and_clean_data
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - uses: actions/setup-python@v4 # THIS IS IMPORTANT
      with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
    - name: download source data
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        pip install -r requirements_runner.txt
        python3 vectorize_text.py
