name: Training pipeline222
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - name: deploy
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        sudo apt update
        sudo apt install python3.9
        pip install -r requirements_runner.txt
        RUNNER_TRACKING_ID="" && nohup python3 web_inference.py
  
