name: Training pipeline222
on:
  workflow_dispatch:


jobs:
  train_models:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master # THIS IS IMPORTANT
    - name: train_models
      env:
        MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
        MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
      run: |
        sudo apt update
        sudo apt install python3.9
        pip install -r requirements_runner.txt
        python3 train.py

  
